name 'proteon-nginx'
version '0.1.8'

author 'Proteon'
license 'Apache License, Version 2.0'
project_page 'http://github.com/Proteon/puppet-nginx'
source 'git://github.com/Proteon/puppet-nginx.git'
summary 'Nginx module'
description 'Puppet code for deploying and configuring Nginx on Debian-like servers'
dependency 'ripienaar/concat', '>=0.2.0'
dependency 'puppetlabs/stdlib', '>=3.2.0'
