name 'proteon-nginx'
version '0.1'
source 'git://github.com/Proteon/puppet-nginx.git'
author 'Proteon'
license 'Apache'
summary 'Nginx module'
description 'Puppet code for deploying and configuring Nginx on Debian-like servers'
project_page 'http://github.com/Proteon/puppet-nginx'
